apiVersion: v1
kind: Service
metadata:
  name: hashresponse-svc 
spec:
  type: NodePort
  selector:
    app: hashresponse 
  ports:
  - port: 1234
    name: http
    nodePort: 30080
    protocol: TCP
    targetPort: 3000
