apiVersion: apps/v1
kind: Deployment
metadata:
  name: timestamp-string-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timestamp-string 
  template:
    metadata:
      labels:
        app: timestamp-string 
    spec:
      containers:
      - name: timestamp-string 
        image: jimryan/timestamp-string@sha256:88ce46669d4502c33f2159479f49dac452cf1169085e05ea5ec1041f6d6e7d61
        imagePullPolicy: Always
