apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-dep 
spec:
  selector:
    matchLabels:
      app: pong 
  template:
    metadata:
      labels:
        app: pong 
    spec:
      volumes:
        - name: persistent-pong 
          persistentVolumeClaim:
            claimName: pong-claim
      containers:
      - name: pong 
        image: jimryan/pong@sha256:82cc62ed02ab472e8452e49fe0ea2c1b2620891bf30d8f994ffbcf71cf695081
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: persistent-pong
            mountPath: /tmp/kube
